server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848      #本地windows版nacos单机
        server-addr: 192.168.44.129:1111  #Linux版Nacos集群

management:
  endpoints:
    web:
      exposure:
        include: '*'